package portal

import (
	"embed"
	"io"
	"io/fs"
	"net/http"
	"strings"
)

// portalSPA is the production build of the React portal (vite build
// output). The directory is generated by `npm run build` inside
// portal-ui/. CI is responsible for running the build before `go build`.
//
// When portal-ui/dist/ is absent (clean checkout, no npm build run),
// the embed below resolves to an empty FS. The SPAHandler falls
// through to a small placeholder page so the binary still boots.
//
//go:embed all:spa_dist
var portalSPA embed.FS

// SPAHandler returns an http.Handler that serves the embedded portal
// SPA. Behavior:
//
//   - GET /assets/<file>     → serve the static asset (cached forever)
//   - GET /favicon.svg etc.  → serve from spa_dist root
//   - GET /<any other path>  → serve spa_dist/index.html (SPA routing)
//   - When spa_dist is empty → "portal SPA not bundled" placeholder
//
// Mount this AFTER the /api/portal/* routes — the issuer main does
// that via the rootMux pattern.
func SPAHandler() http.Handler {
	sub, err := fs.Sub(portalSPA, "spa_dist")
	if err != nil {
		return placeholderHandler()
	}
	indexBytes, err := fs.ReadFile(sub, "index.html")
	if err != nil {
		// No build present.
		return placeholderHandler()
	}
	fileServer := http.FileServer(http.FS(sub))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := strings.TrimPrefix(r.URL.Path, "/")
		// Try to serve the asset directly. If it doesn't exist in the
		// embedded FS, serve index.html so the React router can take it.
		if path == "" {
			serveIndex(w, indexBytes)
			return
		}
		f, err := sub.Open(path)
		if err != nil {
			serveIndex(w, indexBytes)
			return
		}
		_ = f.Close()
		// Long cache for hashed asset files, short for everything else.
		if strings.HasPrefix(path, "assets/") {
			w.Header().Set("Cache-Control", "public, max-age=31536000, immutable")
		} else {
			w.Header().Set("Cache-Control", "no-cache")
		}
		fileServer.ServeHTTP(w, r)
	})
}

func serveIndex(w http.ResponseWriter, b []byte) {
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = io.Copy(w, strings.NewReader(string(b)))
}

func placeholderHandler() http.Handler {
	const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>infraYS Portal</title>
<style>body{background:#0b0f17;color:#e6e8ef;font-family:system-ui;display:flex;align-items:center;justify-content:center;min-height:100vh;margin:0}
.card{background:#111727;border:1px solid #1a2236;padding:2rem;border-radius:8px;max-width:480px}
h1{margin:0 0 1rem;font-size:1.25rem}p{color:#9aa3b2;line-height:1.5;font-size:.9rem}</style></head>
<body><div class="card"><h1>infraYS Portal</h1>
<p>The portal frontend isn't bundled into this binary build. Run <code>npm run build</code> in <code>portal-ui/</code> and rebuild the Go binary.</p></div></body></html>`
	return http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
		w.Header().Set("Content-Type", "text/html; charset=utf-8")
		_, _ = w.Write([]byte(html))
	})
}
