// Package store holds the data types and the persistence interface
// used by the issuer service. Phase 49 ships an in-memory
// implementation in memory.go; the PostgreSQL adapter lands in a
// follow-up commit when the operational infrastructure (RDS / Cloud
// SQL) is provisioned.
//
// Identifiers are opaque strings rather than UUIDs at the Go level —
// the service does not need to interpret them, only to store and
// look up. The choice of format (UUIDv4, ULID, KSUID, prefix_hex)
// belongs to whoever generates them.
package store

import "time"

// Customer represents one paying party. Owns subscriptions and
// deployments. Identified by an email that is unique across the
// system.
//
// Phase 52 adds the password / email verification / reset fields
// for the customer portal at app.infrays.org. These are nullable
// to keep backward compat with customers created pre-portal via
// the admin endpoints or Stripe Checkout (which don't set a
// password until the customer claims their account via the
// "set up your portal access" email flow).
type Customer struct {
	ID               string    // "cust_..."; opaque, generated by issuer
	Email            string    // unique
	Name             string    // display name; optional
	Company          string    // optional
	StripeCustomerID string    // empty for offline customers
	Status           string    // active | suspended | deleted
	CreatedAt        time.Time
	UpdatedAt        time.Time

	// Phase 52: portal credentials. Optional — customers created via
	// admin endpoints / Stripe Checkout have empty PasswordHash until
	// they complete portal signup.
	PasswordHash    string    // bcrypt; empty = no portal access yet
	EmailVerifiedAt time.Time // zero = unverified
	// Password-reset / email-verification token. Single-use; cleared
	// after redemption. Caller stores the SHA-256 hash of the token,
	// not the plaintext (the plaintext is emailed once).
	TokenHash    string
	TokenExpires time.Time
	TokenPurpose string // "verify_email" | "reset_password" | ""
}

// PortalSession is one active browser session for a portal user.
// Cookie value is the session ID; lookups by ID happen on every
// request behind the portal mux.
//
// Phase 52: simple model — no refresh tokens, no remember-me. Cookie
// TTL is 7 days; activity rolls the TTL forward on each request.
type PortalSession struct {
	ID         string    // 32-byte hex string; cookie value
	CustomerID string
	IP         string
	UserAgent  string
	CreatedAt  time.Time
	LastSeen   time.Time
	ExpiresAt  time.Time
}

// Subscription ties a customer to a tier + billing period. Mirrors
// the Stripe subscription state for the customer's active product.
// Offline / sales-issued enterprise customers have a Subscription
// row too — StripeSubscriptionID is empty, ManualOffline is true.
type Subscription struct {
	ID                   string    // "sub_..."; opaque
	CustomerID           string
	Tier                 string    // free | professional | enterprise
	StripeSubscriptionID string    // empty for offline
	StripePriceID        string
	Status               string    // trialing | active | past_due | canceled | incomplete
	CurrentPeriodStart   time.Time
	CurrentPeriodEnd     time.Time
	CancelAt             time.Time // zero if not scheduled to cancel
	CanceledAt           time.Time // zero if not canceled
	TrialEnd             time.Time // zero if no trial
	ManualOffline        bool      // true = sales-issued, no Stripe
	CreatedAt            time.Time
	UpdatedAt            time.Time

	// TrialRemindersSent records which day-threshold reminder emails
	// have already been sent for this trial. Idempotency tracking so
	// the scheduler doesn't send the 7-day reminder seven times in a
	// row. Values are day counts: e.g. [30, 7] means the 30-day and
	// 7-day reminders have fired; the 1-day still hasn't.
	TrialRemindersSent []int
}

// Deployment is a unique NodePulse install. Identified by
// DeploymentID, which the NodePulse server generates on first start
// and persists locally. The issuer records first-seen / last-seen
// purely for support and anomaly detection.
type Deployment struct {
	ID               string    // issuer-side row id "dep_..."
	CustomerID       string
	DeploymentID     string    // UUID generated by NodePulse
	DeploymentName   string    // optional, customer-set
	FirstSeenAt      time.Time
	LastSeenAt       time.Time
	LastVersion      string    // last reported NodePulse version
	FlaggedForReview bool      // anomaly detection set this
	FlagReason       string    // free-text reason
	CreatedAt        time.Time
}

// EnrollmentToken is the one-shot consumable that lets a NodePulse
// install exchange itself for a signed license. Single-use, but
// idempotent for 24h after first redemption (returns the same
// response so a client retry after a network blip doesn't lock out).
type EnrollmentToken struct {
	ID                    string
	CustomerID            string
	SubscriptionID        string
	TokenHash             string    // SHA-256 of plaintext; plaintext shown to user once at creation
	Label                 string    // "prod-cluster-east"
	CreatedAt             time.Time
	ExpiresAt             time.Time // 24h after creation by default
	ConsumedAt            time.Time // zero if not yet redeemed
	ConsumedByDeployment  string    // foreign key into deployments.deployment_id
	ConsumedResponseJWS   string    // cached license JWS for idempotent re-redeem
}

// License is the issuer-side record of a license that has been
// issued. The actual JWS payload is stored as PayloadJWS so we can
// re-serve it on idempotent refresh, audit-trail the exact bytes,
// and verify our own issuance later.
//
// A new License row is created on every successful refresh. JTI
// rotates per issuance; LicenseID is stable across refreshes for
// the same (deployment, subscription).
type License struct {
	ID               string    // issuer-side row id
	JTI              string    // unique per issuance
	LicenseID        string    // stable across refreshes
	CustomerID       string
	SubscriptionID   string
	DeploymentID     string
	EntitlementSetID string
	Tier             string
	Iat              time.Time
	NotBefore        time.Time
	ExpiresAt        time.Time
	GraceUntil       time.Time
	Revoked          bool
	RevokedAt        time.Time
	RevokedReason    string
	Kid              string
	PayloadJWS       string // the full JWS Compact token
	CreatedAt        time.Time
}

// EntitlementSet is the feature manifest pointed to by License.EntitlementSetID.
// Versioned — once published, never edited (publish a new ID instead).
type EntitlementSet struct {
	ID           string // "professional-v2"
	Name         string // "Professional"
	Version      int    // monotonic; 1 = first
	Features     []string
	Limits       Limits
	CreatedAt    time.Time
	DeprecatedAt time.Time // zero if active
}

// Limits is the per-tier ceiling. Copied to the License payload for
// fast local enforcement; the manifest is authoritative on conflict.
type Limits struct {
	MaxAgents        int64
	MaxMetricsPerSec int64
	MaxLogGBPerDay   int64
	MaxAlertRules    int64
	RetentionDays    int
}

// AdminUser is an infraYS staff member who can use the admin
// portal / CLI. Password-authenticated with required MFA.
type AdminUser struct {
	ID           string
	Email        string
	PasswordHash string
	Role         string // admin | support | sales | engineer
	MFASecret    string // TOTP base32; required
	LastLogin    time.Time
	CreatedAt    time.Time
}

// WebhookEvent records every Stripe (or future provider) webhook for
// idempotent replay-safe processing. Stripe retries events on 5xx
// responses; without de-dup we'd double-issue licenses, double-cancel
// subscriptions, etc.
//
// Identified by the provider's own event ID (Stripe assigns "evt_...").
type WebhookEvent struct {
	ID          string    // provider event ID, e.g. "evt_1Abc..."
	Type        string    // "customer.subscription.created"
	Payload     []byte    // raw JSON body (for replay / audit)
	ReceivedAt  time.Time
	ProcessedAt time.Time // zero if pending
	Status      string    // "pending" | "processed" | "failed"
	LastError   string    // populated on Status="failed"
}
